MY_OPENAI_API_KEY = "YOUR OPENAI API"
MY_PINECONE_API_KEY = "YOUR PINECONE API"
MY_IMG_MODEL = "gpt-4o-mini"
MY_IMG_MODEL_HIGH = "gpt-4o"
MY_TXT_MODEL = 'text-embedding-3-small'
MY_GEN_MODEL = 'dall-e-3'
